LAU-948 encryption of reason field on database
hmcts/lau-case-backend pull request #761
Opened 2024-09-10 10:03 UTC by priyankaVerma21

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/LAU-948

### Change description ###
encryption of reason field on database

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-09-11 10:41 UTC, MartinYSpasov requested changes

2024-09-11 10:41 UTC, MartinYSpasov commented on src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestFindRepository.java
> +    private long countResults(final String encryptionKey,
encryptionKey is unused in countResults

2024-09-11 10:41 UTC, MartinYSpasov commented on src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestInsertRepository.java
> +    public AccessRequestInsertRepository(final EntityManager entityManager) {
You could just use @AllArgsConstructor instead?

2024-09-11 10:41 UTC, MartinYSpasov commented on src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestService.java
> +    private final TimestampUtil timestampUtil;
This is unused

2024-09-11 10:43 UTC, MartinYSpasov commented on src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestFindRepository.java
> +public class AccessRequestFindRepository {
I don't see any GET/POST repository tests

2024-09-12 09:57 UTC, MartinYSpasov approved these changes

2024-09-13 09:20 UTC, rapolaskaseliscgi commented on src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/AccessRequestService.java
> +            accessRequest = accessRequestRepository.save(accessRequestLog.toModel());;
Rogue semi-colon at the end.

2024-09-13 09:23 UTC, rapolaskaseliscgi commented on src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/AccessRequestRepositoryTest.java
> +public class AccessRequestRepositoryTest {
Please, remove this `public` modifier.

2024-09-13 09:53 UTC, merged